//대여 기록이 존재하는 자동차 리스트 구분하기

//WHERE와 HAVING에 대해 찾아보자.
SELECT C.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR C JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H ON C.CAR_ID = H.CAR_ID
WHERE C.CAR_TYPE = '세단' AND H.START_DATE LIKE '2022-10%'
GROUP BY H.CAR_ID
ORDER BY C.CAR_ID DESC;