//조건에 부합하는 중고거래 상태 조회하기

//CASE WHEN(조건) THEN  END 문을 사용하여, 조건문과 동일한 작동을 사용할 수 있다.
SELECT BOARD_ID, WRITER_ID, TITLE, PRICE, CASE
    WHEN STATUS = 'SALE' THEN '판매중'
    WHEN STATUS = 'RESERVED' THEN '예약중'
    WHEN STATUS = 'DONE' THEN '거래완료'
    END AS STATUS
FROM USED_GOODS_BOARD
WHERE CREATED_DATE LIKE '2022-10-05'
ORDER BY BOARD_ID DESC;
